---

- name: Download node-exporter from {{ prometheus_node_exporter_url }}
  get_url:
    url: '{{ prometheus_node_exporter_url }}'
    dest: '/home/{{ ansible_user }}'

- name: Create {{ prometheus_node_exporter_install_path }} dir
  file:
    path: '{{ prometheus_node_exporter_install_path }}'
    state: directory

- name: Extract {{ prometheus_node_exporter_archive_name }}
  unarchive:
    src:  '/home/{{ ansible_user }}/{{ prometheus_node_exporter_archive_name }}'
    dest: '{{ prometheus_node_exporter_install_path }}'
    remote_src: True
    extra_opts: [--strip-components=1]

- name: Remove {{ prometheus_node_exporter_archive_name }} archive
  file:
    path: '/home/{{ ansible_user }}/{{ prometheus_node_exporter_archive_name }}'
    state: absent
